Resources:
  PlaylistsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "playlists"

  AlbumTracksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "asin"
          AttributeType: "S"
        - AttributeName: "track_number"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "asin"
          KeyType: "HASH"
        - AttributeName: "track_number"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "album_tracks"

  Type: AWS::Lambda::Function
    Properties:
      Architectures: "x86_64"
      Code:
        ZipFile : "build/distributions/UnitProject.zip"
      CodeSigningConfigArn: "arn:aws:lambda:us-east-2:420509969810:function:GetPlaylistActivityProvider"
      FunctionName: "lambdaGetTest"
      Handler: "com.amazon.ata.music.playlist.service.lambda.GetPlaylistActivityProvider::handleRequest"
      Runtime: "Java 11 (Corretto)"